### ISSUE TITLE
Are pub(crate) members intentional?

### ISSUE THREAD

**Issue by erikbrinkman** [Trivernis/asciimath-rs#13]
Currently some of the elements have members with their visibility set to `pub(crate)` which makes it impossible to write external formatters. Is this intentional?

**Comment by Trivernis** [comment]
No it's not intentional. Which types are affected?

**Comment by erikbrinkman** [comment]
For example, lets say I wanted to format a `Number`, as an external crate, I can't access it's `number` field, meaning I can't actually render it meaningfully.

**Comment by Trivernis** [comment]
Oh well, I see. Yeah that needs to be changed.
